name: Deploy & release
on: workflow_dispatch
jobs:
  deploy:
    runs-on: macos-latest
    name: Build APK & Web
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter config --enable-web
      - run: flutter config --enable-macos-desktop
      - run: flitter pub get
      - run: flutter build macos --release
      - run: flutter build apk --debug --split-per-abi

      - name:  Create A Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk,build/macos/Build/Products/Release/*.app"
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: flutter web build

      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: build/web
