name: Test on IOS Device

on: workflow_dispatch

jobs:
  drive_ios:
    strategy:
      matrix:
        device:
          - "iPhone 11"
          - "iPhone 12"
      fail-fast: false

    runs-on: macos-latest

  #  needs: test
    steps:
      - run: sw_vers
      - name: List All Simulators
        run: xcrun xctrace list devices

      - name: Set UDID of device  
        run: UDID=$(xcrun xctrace list devices  | awk -F"[()]" -v "dev=iPhone 11" '$0~dev{print $(NF-1) }')

      - name: Check UDID
        run: echo "$UDID"

      - name: Start Simulator
        run: xcrun simctl boot "${{ matrix.device }}"

      - uses: actions/checkout@v2
      
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Run Flutter Driver Tests
        run: flutter test integration_test/app_test.dart

