name: Test on IOS Device

on: workflow_dispatch

jobs:
  drive_ios:
    strategy:
      matrix:
        device:
          - "iPhone 8 (14.4)"
          - "iPhone 11 Pro Max (14.4)"
      fail-fast: false

    runs-on: macos-latest

  #  needs: test
    steps:
      - run: sw_vers
      - name: List All Simulators
        run: xcrun xctrace list devices

      - name: Start Simulator
        run: |
          UDID=$(
                       xcrun xctrace list devices |
                       awk \
                         -F ' *[][]' \
                         -v 'device=${{ matrix.device }}' \
                         '$1 == device { print $2 }'
                     )
          xcrun simctl boot 6411260A-0960-47A1-9F3B-D03A0406D26F

      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Run Flutter Driver Tests
        run: flutter drive --target=test_driver/app.dart
